"""initial schema

Revision ID: 2cb2e7418b06
Revises: 
Create Date: 2026-10-07 23:00:34.985600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2cb2e7418b06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Các bảng có UpdatedAt được database trigger BEFORE UPDATE cập nhật (docs/database-schema.md).
UPDATED_AT_TABLES = ("Users", "Products", "Carts", "Reviews")

# Toàn bộ 36 bảng: bật RLS (không policy) và REVOKE quyền của anon/authenticated.
# Backend dùng role postgres (BYPASSRLS); React không truy cập bảng qua Supabase Data API.
ALL_TABLES = (
    "Users",
    "Addresses",
    "Notifications",
    "Categories",
    "Brands",
    "Products",
    "ProductVariants",
    "ProductImages",
    "ProductSerials",
    "Wishlists",
    "WishlistItems",
    "Carts",
    "CartItems",
    "ShippingMethods",
    "Orders",
    "OrderItems",
    "OrderStatusHistories",
    "PaymentMethods",
    "PaymentTransactions",
    "Promotions",
    "PromotionProducts",
    "PromotionCategories",
    "Coupons",
    "Suppliers",
    "PurchaseOrders",
    "PurchaseOrderItems",
    "Reviews",
    "ReviewImages",
    "Conversations",
    "Messages",
    "WarrantyRequests",
    "ReturnRequests",
    "ServiceRequestAttachments",
    "ServiceRequestHistories",
    "NewsArticles",
    "Banners",
)
DATA_API_ROLES = "anon, authenticated"


def upgrade() -> None:
    """Upgrade schema."""
    # Viết thủ công: function cho trigger UpdatedAt.
    op.execute(
        """
        CREATE FUNCTION public.set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = ''
        AS $$
        BEGIN
            NEW."UpdatedAt" := now();
            RETURN NEW;
        END;
        $$
        """
    )
    # PostgreSQL mặc định cấp EXECUTE cho PUBLIC; trigger function không cần quyền này.
    op.execute("REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brands',
    sa.Column('BrandId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Slug', sa.String(length=300), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('LogoUrl', sa.String(length=500), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('BrandId', name=op.f('PK_Brands')),
    sa.UniqueConstraint('Slug', name=op.f('UQ_Brands_Slug'))
    )
    op.create_table('Categories',
    sa.Column('CategoryId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ParentCategoryId', sa.UUID(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Slug', sa.String(length=300), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DisplayOrder', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ParentCategoryId'], ['Categories.CategoryId'], name=op.f('FK_Categories_ParentCategoryId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('CategoryId', name=op.f('PK_Categories')),
    sa.UniqueConstraint('Slug', name=op.f('UQ_Categories_Slug'))
    )
    op.create_table('PaymentMethods',
    sa.Column('PaymentMethodId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('DisplayOrder', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('PaymentMethodId', name=op.f('PK_PaymentMethods')),
    sa.UniqueConstraint('Code', name=op.f('UQ_PaymentMethods_Code'))
    )
    op.create_table('ShippingMethods',
    sa.Column('ShippingMethodId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('BaseFee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('EstimatedDays', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('"BaseFee" >= 0', name=op.f('CK_ShippingMethods_BaseFee_NonNegative')),
    sa.PrimaryKeyConstraint('ShippingMethodId', name=op.f('PK_ShippingMethods')),
    sa.UniqueConstraint('Code', name=op.f('UQ_ShippingMethods_Code'))
    )
    op.create_table('Suppliers',
    sa.Column('SupplierId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('SupplierCode', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=False),
    sa.Column('Address', sa.String(length=500), nullable=False),
    sa.Column('TaxCode', sa.String(length=20), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SupplierId', name=op.f('PK_Suppliers')),
    sa.UniqueConstraint('SupplierCode', name=op.f('UQ_Suppliers_SupplierCode'))
    )
    op.create_table('Users',
    sa.Column('UserId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('FullName', sa.String(length=255), nullable=False),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('AvatarUrl', sa.String(length=500), nullable=True),
    sa.Column('Role', sa.String(length=20), nullable=False),
    sa.Column('AccountStatus', sa.String(length=20), nullable=False),
    sa.Column('IsEmailVerified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('OtpCode', sa.String(length=10), nullable=True),
    sa.Column('OtpExpiredAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('LockReason', sa.Text(), nullable=True),
    sa.Column('LockedUntil', sa.DateTime(timezone=True), nullable=True),
    sa.Column('TotalSpent', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('TotalOrders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('"Role" IN (\'Customer\', \'Staff\', \'Admin\', \'SuperAdmin\')', name=op.f('CK_Users_Role_Valid')),
    sa.CheckConstraint('"TotalOrders" >= 0', name=op.f('CK_Users_TotalOrders_NonNegative')),
    sa.CheckConstraint('"TotalSpent" >= 0', name=op.f('CK_Users_TotalSpent_NonNegative')),
    sa.PrimaryKeyConstraint('UserId', name=op.f('PK_Users')),
    sa.UniqueConstraint('PhoneNumber', name=op.f('UQ_Users_PhoneNumber'))
    )
    op.create_index('UX_Users_Email_Lower', 'Users', [sa.literal_column('lower("Email")')], unique=True)
    op.create_table('Addresses',
    sa.Column('AddressId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('ReceiverName', sa.String(length=255), nullable=False),
    sa.Column('ReceiverPhone', sa.String(length=20), nullable=False),
    sa.Column('Province', sa.String(length=100), nullable=False),
    sa.Column('Ward', sa.String(length=100), nullable=False),
    sa.Column('DetailAddress', sa.String(length=255), nullable=False),
    sa.Column('IsDefault', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Addresses_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AddressId', name=op.f('PK_Addresses'))
    )
    op.create_table('Banners',
    sa.Column('BannerId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CreatedByUserId', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=False),
    sa.Column('LinkUrl', sa.String(length=500), nullable=True),
    sa.Column('DisplayOrder', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('StartDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('EndDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"EndDate" >= "StartDate"', name=op.f('CK_Banners_EndDate_AfterStartDate')),
    sa.ForeignKeyConstraint(['CreatedByUserId'], ['Users.UserId'], name=op.f('FK_Banners_CreatedByUserId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('BannerId', name=op.f('PK_Banners'))
    )
    op.create_table('Carts',
    sa.Column('CartId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Carts_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CartId', name=op.f('PK_Carts')),
    sa.UniqueConstraint('UserId', name=op.f('UQ_Carts_UserId'))
    )
    op.create_table('Conversations',
    sa.Column('ConversationId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CustomerId', sa.UUID(), nullable=False),
    sa.Column('AssignedStaffId', sa.UUID(), nullable=True),
    sa.Column('Mode', sa.String(length=20), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ClosedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"Status" IN (\'Open\', \'Closed\')', name=op.f('CK_Conversations_Status_Valid')),
    sa.ForeignKeyConstraint(['AssignedStaffId'], ['Users.UserId'], name=op.f('FK_Conversations_AssignedStaffId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['CustomerId'], ['Users.UserId'], name=op.f('FK_Conversations_CustomerId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ConversationId', name=op.f('PK_Conversations'))
    )
    op.create_table('NewsArticles',
    sa.Column('NewsArticleId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CreatedByUserId', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Slug', sa.String(length=300), nullable=False),
    sa.Column('Summary', sa.Text(), nullable=True),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('ThumbnailUrl', sa.String(length=500), nullable=True),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('PublishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"Status" IN (\'Draft\', \'Published\', \'Hidden\')', name=op.f('CK_NewsArticles_Status_Valid')),
    sa.ForeignKeyConstraint(['CreatedByUserId'], ['Users.UserId'], name=op.f('FK_NewsArticles_CreatedByUserId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('NewsArticleId', name=op.f('PK_NewsArticles')),
    sa.UniqueConstraint('Slug', name=op.f('UQ_NewsArticles_Slug'))
    )
    op.create_table('Notifications',
    sa.Column('NotificationId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('NotificationType', sa.String(length=50), nullable=False),
    sa.Column('ActionUrl', sa.String(length=500), nullable=True),
    sa.Column('ReferenceType', sa.String(length=50), nullable=True),
    sa.Column('ReferenceId', sa.UUID(), nullable=True),
    sa.Column('IsRead', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ReadAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Notifications_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('NotificationId', name=op.f('PK_Notifications'))
    )
    op.create_table('Products',
    sa.Column('ProductId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CategoryId', sa.UUID(), nullable=False),
    sa.Column('BrandId', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Slug', sa.String(length=300), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('WarrantyMonths', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('AverageRating', sa.Numeric(precision=3, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('ReviewCount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('SoldQuantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('"AverageRating" BETWEEN 0 AND 5', name=op.f('CK_Products_AverageRating_Range')),
    sa.CheckConstraint('"ReviewCount" >= 0', name=op.f('CK_Products_ReviewCount_NonNegative')),
    sa.CheckConstraint('"SoldQuantity" >= 0', name=op.f('CK_Products_SoldQuantity_NonNegative')),
    sa.CheckConstraint('"Status" IN (\'Draft\', \'Active\', \'Inactive\', \'Discontinued\')', name=op.f('CK_Products_Status_Valid')),
    sa.ForeignKeyConstraint(['BrandId'], ['Brands.BrandId'], name=op.f('FK_Products_BrandId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.CategoryId'], name=op.f('FK_Products_CategoryId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ProductId', name=op.f('PK_Products')),
    sa.UniqueConstraint('Slug', name=op.f('UQ_Products_Slug'))
    )
    op.create_table('Promotions',
    sa.Column('PromotionId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CreatedByUserId', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DiscountType', sa.String(length=20), nullable=False),
    sa.Column('DiscountValue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('MinOrderValue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('MaxDiscountAmount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('StartDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('EndDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"DiscountType" <> \'Percentage\' OR "DiscountValue" <= 100', name=op.f('CK_Promotions_DiscountValue_PercentageMax')),
    sa.CheckConstraint('"DiscountType" IN (\'Percentage\', \'FixedAmount\')', name=op.f('CK_Promotions_DiscountType_Valid')),
    sa.CheckConstraint('"DiscountValue" >= 0', name=op.f('CK_Promotions_DiscountValue_NonNegative')),
    sa.CheckConstraint('"EndDate" >= "StartDate"', name=op.f('CK_Promotions_EndDate_AfterStartDate')),
    sa.CheckConstraint('"MaxDiscountAmount" >= 0', name=op.f('CK_Promotions_MaxDiscountAmount_NonNegative')),
    sa.CheckConstraint('"MinOrderValue" >= 0', name=op.f('CK_Promotions_MinOrderValue_NonNegative')),
    sa.CheckConstraint('"Status" IN (\'Draft\', \'Scheduled\', \'Active\', \'Expired\', \'Cancelled\')', name=op.f('CK_Promotions_Status_Valid')),
    sa.ForeignKeyConstraint(['CreatedByUserId'], ['Users.UserId'], name=op.f('FK_Promotions_CreatedByUserId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('PromotionId', name=op.f('PK_Promotions'))
    )
    op.create_table('PurchaseOrders',
    sa.Column('PurchaseOrderId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('PurchaseOrderCode', sa.String(length=50), nullable=False),
    sa.Column('SupplierId', sa.UUID(), nullable=False),
    sa.Column('CreatedByUserId', sa.UUID(), nullable=False),
    sa.Column('DecidedByUserId', sa.UUID(), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.Column('RejectReason', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('DecidedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"Status" IN (\'Pending\', \'Approved\', \'Rejected\', \'Receiving\', \'Completed\', \'Cancelled\')', name=op.f('CK_PurchaseOrders_Status_Valid')),
    sa.CheckConstraint('"TotalAmount" >= 0', name=op.f('CK_PurchaseOrders_TotalAmount_NonNegative')),
    sa.ForeignKeyConstraint(['CreatedByUserId'], ['Users.UserId'], name=op.f('FK_PurchaseOrders_CreatedByUserId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['DecidedByUserId'], ['Users.UserId'], name=op.f('FK_PurchaseOrders_DecidedByUserId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['SupplierId'], ['Suppliers.SupplierId'], name=op.f('FK_PurchaseOrders_SupplierId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('PurchaseOrderId', name=op.f('PK_PurchaseOrders')),
    sa.UniqueConstraint('PurchaseOrderCode', name=op.f('UQ_PurchaseOrders_PurchaseOrderCode'))
    )
    op.create_table('Wishlists',
    sa.Column('WishlistId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Wishlists_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WishlistId', name=op.f('PK_Wishlists')),
    sa.UniqueConstraint('UserId', name=op.f('UQ_Wishlists_UserId'))
    )
    op.create_table('Coupons',
    sa.Column('CouponId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('PromotionId', sa.UUID(), nullable=False),
    sa.Column('CreatedByUserId', sa.UUID(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UsageLimit', sa.Integer(), nullable=True),
    sa.Column('UsedCount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"UsageLimit" >= 0', name=op.f('CK_Coupons_UsageLimit_NonNegative')),
    sa.CheckConstraint('"UsedCount" >= 0', name=op.f('CK_Coupons_UsedCount_NonNegative')),
    sa.ForeignKeyConstraint(['CreatedByUserId'], ['Users.UserId'], name=op.f('FK_Coupons_CreatedByUserId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['PromotionId'], ['Promotions.PromotionId'], name=op.f('FK_Coupons_PromotionId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('CouponId', name=op.f('PK_Coupons')),
    sa.UniqueConstraint('Code', name=op.f('UQ_Coupons_Code'))
    )
    op.create_table('Messages',
    sa.Column('MessageId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ConversationId', sa.UUID(), nullable=False),
    sa.Column('SenderUserId', sa.UUID(), nullable=True),
    sa.Column('SenderType', sa.String(length=20), nullable=False),
    sa.Column('MessageType', sa.String(length=20), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('IsRead', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('SentAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ConversationId'], ['Conversations.ConversationId'], name=op.f('FK_Messages_ConversationId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SenderUserId'], ['Users.UserId'], name=op.f('FK_Messages_SenderUserId'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('MessageId', name=op.f('PK_Messages'))
    )
    op.create_table('ProductImages',
    sa.Column('ProductImageId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ProductId', sa.UUID(), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=False),
    sa.Column('DisplayOrder', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('IsDefault', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.ProductId'], name=op.f('FK_ProductImages_ProductId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ProductImageId', name=op.f('PK_ProductImages'))
    )
    op.create_table('ProductVariants',
    sa.Column('ProductVariantId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ProductId', sa.UUID(), nullable=False),
    sa.Column('Sku', sa.String(length=50), nullable=False),
    sa.Column('VariantName', sa.String(length=255), nullable=False),
    sa.Column('Color', sa.String(length=50), nullable=True),
    sa.Column('Storage', sa.String(length=50), nullable=True),
    sa.Column('Price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('CostPrice', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('MinStockLevel', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('"CostPrice" >= 0', name=op.f('CK_ProductVariants_CostPrice_NonNegative')),
    sa.CheckConstraint('"MinStockLevel" >= 0', name=op.f('CK_ProductVariants_MinStockLevel_NonNegative')),
    sa.CheckConstraint('"Price" >= 0', name=op.f('CK_ProductVariants_Price_NonNegative')),
    sa.CheckConstraint('"StockQuantity" >= 0', name=op.f('CK_ProductVariants_StockQuantity_NonNegative')),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.ProductId'], name=op.f('FK_ProductVariants_ProductId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ProductVariantId', name=op.f('PK_ProductVariants')),
    sa.UniqueConstraint('Sku', name=op.f('UQ_ProductVariants_Sku'))
    )
    op.create_table('PromotionCategories',
    sa.Column('PromotionId', sa.UUID(), nullable=False),
    sa.Column('CategoryId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.CategoryId'], name=op.f('FK_PromotionCategories_CategoryId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PromotionId'], ['Promotions.PromotionId'], name=op.f('FK_PromotionCategories_PromotionId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PromotionId', 'CategoryId', name=op.f('PK_PromotionCategories'))
    )
    op.create_table('PromotionProducts',
    sa.Column('PromotionId', sa.UUID(), nullable=False),
    sa.Column('ProductId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.ProductId'], name=op.f('FK_PromotionProducts_ProductId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PromotionId'], ['Promotions.PromotionId'], name=op.f('FK_PromotionProducts_PromotionId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PromotionId', 'ProductId', name=op.f('PK_PromotionProducts'))
    )
    op.create_table('WishlistItems',
    sa.Column('WishlistItemId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('WishlistId', sa.UUID(), nullable=False),
    sa.Column('ProductId', sa.UUID(), nullable=False),
    sa.Column('AddedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.ProductId'], name=op.f('FK_WishlistItems_ProductId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WishlistId'], ['Wishlists.WishlistId'], name=op.f('FK_WishlistItems_WishlistId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WishlistItemId', name=op.f('PK_WishlistItems')),
    sa.UniqueConstraint('WishlistId', 'ProductId', name=op.f('UQ_WishlistItems_WishlistId_ProductId'))
    )
    op.create_table('CartItems',
    sa.Column('CartItemId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('CartId', sa.UUID(), nullable=False),
    sa.Column('ProductVariantId', sa.UUID(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('IsSelected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('AddedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"Quantity" > 0', name=op.f('CK_CartItems_Quantity_Positive')),
    sa.CheckConstraint('"UnitPrice" >= 0', name=op.f('CK_CartItems_UnitPrice_NonNegative')),
    sa.ForeignKeyConstraint(['CartId'], ['Carts.CartId'], name=op.f('FK_CartItems_CartId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ProductVariantId'], ['ProductVariants.ProductVariantId'], name=op.f('FK_CartItems_ProductVariantId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CartItemId', name=op.f('PK_CartItems')),
    sa.UniqueConstraint('CartId', 'ProductVariantId', name=op.f('UQ_CartItems_CartId_ProductVariantId'))
    )
    op.create_table('Orders',
    sa.Column('OrderId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('OrderCode', sa.String(length=50), nullable=False),
    sa.Column('CustomerId', sa.UUID(), nullable=False),
    sa.Column('AssignedStaffId', sa.UUID(), nullable=True),
    sa.Column('AddressId', sa.UUID(), nullable=True),
    sa.Column('ShippingMethodId', sa.UUID(), nullable=False),
    sa.Column('PaymentMethodId', sa.UUID(), nullable=False),
    sa.Column('CouponId', sa.UUID(), nullable=True),
    sa.Column('Subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ShippingFee', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('DiscountAmount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('OrderStatus', sa.String(length=30), nullable=False),
    sa.Column('PaymentStatus', sa.String(length=30), nullable=False),
    sa.Column('ReceiverName', sa.String(length=255), nullable=False),
    sa.Column('ReceiverPhone', sa.String(length=20), nullable=False),
    sa.Column('ShippingAddress', sa.String(length=500), nullable=False),
    sa.Column('CustomerNote', sa.Text(), nullable=True),
    sa.Column('InternalNote', sa.Text(), nullable=True),
    sa.Column('CancelReason', sa.Text(), nullable=True),
    sa.Column('OrderedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ConfirmedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ShippedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DeliveredAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CompletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CancelledAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"DiscountAmount" >= 0', name=op.f('CK_Orders_DiscountAmount_NonNegative')),
    sa.CheckConstraint('"OrderStatus" IN (\'Pending\', \'Confirmed\', \'Processing\', \'Shipping\', \'Delivered\', \'Completed\', \'Cancelled\')', name=op.f('CK_Orders_OrderStatus_Valid')),
    sa.CheckConstraint('"PaymentStatus" IN (\'Pending\', \'Paid\', \'Failed\', \'Refunded\', \'Cancelled\')', name=op.f('CK_Orders_PaymentStatus_Valid')),
    sa.CheckConstraint('"ShippingFee" >= 0', name=op.f('CK_Orders_ShippingFee_NonNegative')),
    sa.CheckConstraint('"Subtotal" >= 0', name=op.f('CK_Orders_Subtotal_NonNegative')),
    sa.CheckConstraint('"TotalAmount" >= 0', name=op.f('CK_Orders_TotalAmount_NonNegative')),
    sa.ForeignKeyConstraint(['AddressId'], ['Addresses.AddressId'], name=op.f('FK_Orders_AddressId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['AssignedStaffId'], ['Users.UserId'], name=op.f('FK_Orders_AssignedStaffId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['CouponId'], ['Coupons.CouponId'], name=op.f('FK_Orders_CouponId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['CustomerId'], ['Users.UserId'], name=op.f('FK_Orders_CustomerId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['PaymentMethodId'], ['PaymentMethods.PaymentMethodId'], name=op.f('FK_Orders_PaymentMethodId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ShippingMethodId'], ['ShippingMethods.ShippingMethodId'], name=op.f('FK_Orders_ShippingMethodId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('OrderId', name=op.f('PK_Orders')),
    sa.UniqueConstraint('OrderCode', name=op.f('UQ_Orders_OrderCode'))
    )
    op.create_table('PurchaseOrderItems',
    sa.Column('PurchaseOrderItemId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('PurchaseOrderId', sa.UUID(), nullable=False),
    sa.Column('ProductVariantId', sa.UUID(), nullable=False),
    sa.Column('OrderedQuantity', sa.Integer(), nullable=False),
    sa.Column('ReceivedQuantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('LineTotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.CheckConstraint('"LineTotal" >= 0', name=op.f('CK_PurchaseOrderItems_LineTotal_NonNegative')),
    sa.CheckConstraint('"OrderedQuantity" > 0', name=op.f('CK_PurchaseOrderItems_OrderedQuantity_Positive')),
    sa.CheckConstraint('"ReceivedQuantity" <= "OrderedQuantity"', name=op.f('CK_PurchaseOrderItems_ReceivedQuantity_NotExceedOrdered')),
    sa.CheckConstraint('"ReceivedQuantity" >= 0', name=op.f('CK_PurchaseOrderItems_ReceivedQuantity_NonNegative')),
    sa.CheckConstraint('"UnitPrice" >= 0', name=op.f('CK_PurchaseOrderItems_UnitPrice_NonNegative')),
    sa.ForeignKeyConstraint(['ProductVariantId'], ['ProductVariants.ProductVariantId'], name=op.f('FK_PurchaseOrderItems_ProductVariantId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['PurchaseOrderId'], ['PurchaseOrders.PurchaseOrderId'], name=op.f('FK_PurchaseOrderItems_PurchaseOrderId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PurchaseOrderItemId', name=op.f('PK_PurchaseOrderItems'))
    )
    op.create_table('OrderItems',
    sa.Column('OrderItemId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('OrderId', sa.UUID(), nullable=False),
    sa.Column('ProductVariantId', sa.UUID(), nullable=False),
    sa.Column('ProductName', sa.String(length=255), nullable=False),
    sa.Column('Sku', sa.String(length=50), nullable=False),
    sa.Column('VariantInfo', sa.String(length=255), nullable=False),
    sa.Column('WarrantyMonths', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('UnitCost', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('DiscountAmount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('LineTotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('"DiscountAmount" >= 0', name=op.f('CK_OrderItems_DiscountAmount_NonNegative')),
    sa.CheckConstraint('"LineTotal" >= 0', name=op.f('CK_OrderItems_LineTotal_NonNegative')),
    sa.CheckConstraint('"Quantity" > 0', name=op.f('CK_OrderItems_Quantity_Positive')),
    sa.CheckConstraint('"UnitCost" >= 0', name=op.f('CK_OrderItems_UnitCost_NonNegative')),
    sa.CheckConstraint('"UnitPrice" >= 0', name=op.f('CK_OrderItems_UnitPrice_NonNegative')),
    sa.ForeignKeyConstraint(['OrderId'], ['Orders.OrderId'], name=op.f('FK_OrderItems_OrderId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ProductVariantId'], ['ProductVariants.ProductVariantId'], name=op.f('FK_OrderItems_ProductVariantId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('OrderItemId', name=op.f('PK_OrderItems'))
    )
    op.create_table('OrderStatusHistories',
    sa.Column('OrderStatusHistoryId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('OrderId', sa.UUID(), nullable=False),
    sa.Column('ChangedByUserId', sa.UUID(), nullable=True),
    sa.Column('OldStatus', sa.String(length=30), nullable=True),
    sa.Column('NewStatus', sa.String(length=30), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.Column('ChangedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"NewStatus" IN (\'Pending\', \'Confirmed\', \'Processing\', \'Shipping\', \'Delivered\', \'Completed\', \'Cancelled\')', name=op.f('CK_OrderStatusHistories_NewStatus_Valid')),
    sa.CheckConstraint('"OldStatus" IN (\'Pending\', \'Confirmed\', \'Processing\', \'Shipping\', \'Delivered\', \'Completed\', \'Cancelled\')', name=op.f('CK_OrderStatusHistories_OldStatus_Valid')),
    sa.ForeignKeyConstraint(['ChangedByUserId'], ['Users.UserId'], name=op.f('FK_OrderStatusHistories_ChangedByUserId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['OrderId'], ['Orders.OrderId'], name=op.f('FK_OrderStatusHistories_OrderId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('OrderStatusHistoryId', name=op.f('PK_OrderStatusHistories'))
    )
    op.create_table('PaymentTransactions',
    sa.Column('PaymentTransactionId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('OrderId', sa.UUID(), nullable=False),
    sa.Column('PaymentMethodId', sa.UUID(), nullable=False),
    sa.Column('GatewayTransactionCode', sa.String(length=100), nullable=True),
    sa.Column('TransactionType', sa.String(length=20), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('QrData', sa.Text(), nullable=True),
    sa.Column('ResponseData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('PaidAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"Amount" >= 0', name=op.f('CK_PaymentTransactions_Amount_NonNegative')),
    sa.CheckConstraint('"Status" IN (\'Pending\', \'Success\', \'Failed\', \'Cancelled\', \'Refunded\')', name=op.f('CK_PaymentTransactions_Status_Valid')),
    sa.ForeignKeyConstraint(['OrderId'], ['Orders.OrderId'], name=op.f('FK_PaymentTransactions_OrderId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['PaymentMethodId'], ['PaymentMethods.PaymentMethodId'], name=op.f('FK_PaymentTransactions_PaymentMethodId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('PaymentTransactionId', name=op.f('PK_PaymentTransactions'))
    )
    op.create_table('ProductSerials',
    sa.Column('ProductSerialId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ProductVariantId', sa.UUID(), nullable=False),
    sa.Column('OrderItemId', sa.UUID(), nullable=True),
    sa.Column('SerialNumber', sa.String(length=100), nullable=False),
    sa.Column('WarrantyStartDate', sa.Date(), nullable=True),
    sa.Column('WarrantyEndDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.CheckConstraint('"Status" IN (\'Available\', \'Reserved\', \'Sold\', \'Warranty\', \'Returned\')', name=op.f('CK_ProductSerials_Status_Valid')),
    sa.ForeignKeyConstraint(['OrderItemId'], ['OrderItems.OrderItemId'], name=op.f('FK_ProductSerials_OrderItemId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ProductVariantId'], ['ProductVariants.ProductVariantId'], name=op.f('FK_ProductSerials_ProductVariantId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ProductSerialId', name=op.f('PK_ProductSerials')),
    sa.UniqueConstraint('SerialNumber', name=op.f('UQ_ProductSerials_SerialNumber'))
    )
    op.create_table('ReturnRequests',
    sa.Column('ReturnRequestId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('RequestCode', sa.String(length=50), nullable=False),
    sa.Column('CustomerId', sa.UUID(), nullable=False),
    sa.Column('AssignedStaffId', sa.UUID(), nullable=True),
    sa.Column('OrderItemId', sa.UUID(), nullable=False),
    sa.Column('RequestType', sa.String(length=20), nullable=False),
    sa.Column('Reason', sa.Text(), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('DecisionReason', sa.Text(), nullable=True),
    sa.Column('DamageAssessment', sa.Text(), nullable=True),
    sa.Column('ResolutionType', sa.String(length=30), nullable=True),
    sa.Column('CompensationAmount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('RequestedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ReceivedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CompletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"CompensationAmount" >= 0', name=op.f('CK_ReturnRequests_CompensationAmount_NonNegative')),
    sa.CheckConstraint('"Status" IN (\'Pending\', \'Approved\', \'Rejected\', \'Receiving\', \'Processing\', \'Completed\', \'Cancelled\')', name=op.f('CK_ReturnRequests_Status_Valid')),
    sa.ForeignKeyConstraint(['AssignedStaffId'], ['Users.UserId'], name=op.f('FK_ReturnRequests_AssignedStaffId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['CustomerId'], ['Users.UserId'], name=op.f('FK_ReturnRequests_CustomerId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['OrderItemId'], ['OrderItems.OrderItemId'], name=op.f('FK_ReturnRequests_OrderItemId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ReturnRequestId', name=op.f('PK_ReturnRequests')),
    sa.UniqueConstraint('RequestCode', name=op.f('UQ_ReturnRequests_RequestCode'))
    )
    op.create_table('Reviews',
    sa.Column('ReviewId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('ProductId', sa.UUID(), nullable=False),
    sa.Column('OrderItemId', sa.UUID(), nullable=False),
    sa.Column('Rating', sa.SmallInteger(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('DeleteReason', sa.Text(), nullable=True),
    sa.Column('DeletedByUserId', sa.UUID(), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"Rating" BETWEEN 1 AND 5', name=op.f('CK_Reviews_Rating_Range')),
    sa.ForeignKeyConstraint(['DeletedByUserId'], ['Users.UserId'], name=op.f('FK_Reviews_DeletedByUserId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['OrderItemId'], ['OrderItems.OrderItemId'], name=op.f('FK_Reviews_OrderItemId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.ProductId'], name=op.f('FK_Reviews_ProductId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Reviews_UserId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ReviewId', name=op.f('PK_Reviews')),
    sa.UniqueConstraint('OrderItemId', name=op.f('UQ_Reviews_OrderItemId'))
    )
    op.create_table('ReviewImages',
    sa.Column('ReviewImageId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ReviewId', sa.UUID(), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=False),
    sa.Column('DisplayOrder', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['ReviewId'], ['Reviews.ReviewId'], name=op.f('FK_ReviewImages_ReviewId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReviewImageId', name=op.f('PK_ReviewImages'))
    )
    op.create_table('WarrantyRequests',
    sa.Column('WarrantyRequestId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('RequestCode', sa.String(length=50), nullable=False),
    sa.Column('CustomerId', sa.UUID(), nullable=False),
    sa.Column('AssignedStaffId', sa.UUID(), nullable=True),
    sa.Column('OrderItemId', sa.UUID(), nullable=False),
    sa.Column('ProductSerialId', sa.UUID(), nullable=True),
    sa.Column('SupplierId', sa.UUID(), nullable=True),
    sa.Column('IssueDescription', sa.Text(), nullable=False),
    sa.Column('EligibilityStatus', sa.String(length=30), nullable=False),
    sa.Column('EligibilityReason', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('ReceivedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('HandoverCode', sa.String(length=50), nullable=True),
    sa.Column('ServiceCenter', sa.String(length=255), nullable=True),
    sa.Column('HandedOverAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ResultType', sa.String(length=30), nullable=True),
    sa.Column('ResultNote', sa.Text(), nullable=True),
    sa.Column('RequestedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('CompletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"EligibilityStatus" IN (\'Pending\', \'Eligible\', \'Ineligible\')', name=op.f('CK_WarrantyRequests_EligibilityStatus_Valid')),
    sa.CheckConstraint('"Status" IN (\'New\', \'Rejected\', \'HandedOver\', \'Processing\', \'Completed\', \'Cancelled\')', name=op.f('CK_WarrantyRequests_Status_Valid')),
    sa.ForeignKeyConstraint(['AssignedStaffId'], ['Users.UserId'], name=op.f('FK_WarrantyRequests_AssignedStaffId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['CustomerId'], ['Users.UserId'], name=op.f('FK_WarrantyRequests_CustomerId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['OrderItemId'], ['OrderItems.OrderItemId'], name=op.f('FK_WarrantyRequests_OrderItemId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ProductSerialId'], ['ProductSerials.ProductSerialId'], name=op.f('FK_WarrantyRequests_ProductSerialId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['SupplierId'], ['Suppliers.SupplierId'], name=op.f('FK_WarrantyRequests_SupplierId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('WarrantyRequestId', name=op.f('PK_WarrantyRequests')),
    sa.UniqueConstraint('RequestCode', name=op.f('UQ_WarrantyRequests_RequestCode'))
    )
    op.create_table('ServiceRequestAttachments',
    sa.Column('ServiceRequestAttachmentId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('WarrantyRequestId', sa.UUID(), nullable=True),
    sa.Column('ReturnRequestId', sa.UUID(), nullable=True),
    sa.Column('FileUrl', sa.String(length=500), nullable=False),
    sa.Column('FileType', sa.String(length=20), nullable=False),
    sa.Column('UploadedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls("WarrantyRequestId", "ReturnRequestId") = 1', name=op.f('CK_ServiceRequestAttachments_OneServiceRequest')),
    sa.ForeignKeyConstraint(['ReturnRequestId'], ['ReturnRequests.ReturnRequestId'], name=op.f('FK_ServiceRequestAttachments_ReturnRequestId'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WarrantyRequestId'], ['WarrantyRequests.WarrantyRequestId'], name=op.f('FK_ServiceRequestAttachments_WarrantyRequestId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ServiceRequestAttachmentId', name=op.f('PK_ServiceRequestAttachments'))
    )
    op.create_table('ServiceRequestHistories',
    sa.Column('ServiceRequestHistoryId', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('WarrantyRequestId', sa.UUID(), nullable=True),
    sa.Column('ReturnRequestId', sa.UUID(), nullable=True),
    sa.Column('ChangedByUserId', sa.UUID(), nullable=True),
    sa.Column('OldStatus', sa.String(length=30), nullable=True),
    sa.Column('NewStatus', sa.String(length=30), nullable=False),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.Column('ChangedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls("WarrantyRequestId", "ReturnRequestId") = 1', name=op.f('CK_ServiceRequestHistories_OneServiceRequest')),
    sa.ForeignKeyConstraint(['ChangedByUserId'], ['Users.UserId'], name=op.f('FK_ServiceRequestHistories_ChangedByUserId'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ReturnRequestId'], ['ReturnRequests.ReturnRequestId'], name=op.f('FK_ServiceRequestHistories_ReturnRequestId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['WarrantyRequestId'], ['WarrantyRequests.WarrantyRequestId'], name=op.f('FK_ServiceRequestHistories_WarrantyRequestId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ServiceRequestHistoryId', name=op.f('PK_ServiceRequestHistories'))
    )
    # ### end Alembic commands ###

    # Viết thủ công: autogenerate không tạo trigger.
    for table in UPDATED_AT_TABLES:
        op.execute(
            f'CREATE TRIGGER "TR_{table}_SetUpdatedAt" '
            f'BEFORE UPDATE ON "{table}" '
            f"FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()"
        )

    # Viết thủ công: security hardening cho Supabase Data API.
    for table in ALL_TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    for table in ALL_TABLES:
        op.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {DATA_API_ROLES}')
    op.execute(f"REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM {DATA_API_ROLES}")
    # Bảng mới do postgres tạo trong public không còn tự động cấp quyền cho anon/authenticated.
    op.execute(
        f"ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public "
        f"REVOKE ALL PRIVILEGES ON TABLES FROM {DATA_API_ROLES}"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Viết thủ công: xóa trigger trước, sau đó xóa function.
    for table in UPDATED_AT_TABLES:
        op.execute(f'DROP TRIGGER "TR_{table}_SetUpdatedAt" ON "{table}"')
    op.execute("DROP FUNCTION public.set_updated_at()")
    # RLS và REVOKE trên bảng tự mất khi drop bảng.
    # Default privileges giữ nguyên trạng thái đã thu hồi (downgrade không cấp lại quyền cho anon/authenticated).

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ServiceRequestHistories')
    op.drop_table('ServiceRequestAttachments')
    op.drop_table('WarrantyRequests')
    op.drop_table('ReviewImages')
    op.drop_table('Reviews')
    op.drop_table('ReturnRequests')
    op.drop_table('ProductSerials')
    op.drop_table('PaymentTransactions')
    op.drop_table('OrderStatusHistories')
    op.drop_table('OrderItems')
    op.drop_table('PurchaseOrderItems')
    op.drop_table('Orders')
    op.drop_table('CartItems')
    op.drop_table('WishlistItems')
    op.drop_table('PromotionProducts')
    op.drop_table('PromotionCategories')
    op.drop_table('ProductVariants')
    op.drop_table('ProductImages')
    op.drop_table('Messages')
    op.drop_table('Coupons')
    op.drop_table('Wishlists')
    op.drop_table('PurchaseOrders')
    op.drop_table('Promotions')
    op.drop_table('Products')
    op.drop_table('Notifications')
    op.drop_table('NewsArticles')
    op.drop_table('Conversations')
    op.drop_table('Carts')
    op.drop_table('Banners')
    op.drop_table('Addresses')
    op.drop_index('UX_Users_Email_Lower', table_name='Users')
    op.drop_table('Users')
    op.drop_table('Suppliers')
    op.drop_table('ShippingMethods')
    op.drop_table('PaymentMethods')
    op.drop_table('Categories')
    op.drop_table('Brands')
    # ### end Alembic commands ###
